from fastapi import APIRouter
from typing import List, Dict, Any
from pathlib import Path
from datetime import datetime
from app.config import VIDEOS_OUTPUT_DIR, CAROUSELS_OUTPUT_DIR, THUMBNAILS_DIR
from app.core.thumbnail_extractor import extract_thumbnail

router = APIRouter(prefix="/api/media", tags=["Media Explorer"])


@router.get("/generated")
def list_generated_media() -> Dict[str, Any]:
    """Lists videos and carousel albums generated by new-lyrics-2 with cached thumbnails."""
    videos = []
    carousels = []

    # 1. Inspect generated MP4 videos
    if VIDEOS_OUTPUT_DIR.exists():
        for f in VIDEOS_OUTPUT_DIR.glob("*.mp4"):
            stat = f.stat()
            thumb_file = extract_thumbnail(f, THUMBNAILS_DIR)
            thumb_url = f"/media/thumbnails/{thumb_file}" if thumb_file else None

            videos.append({
                "filename": f.name,
                "path": str(f.resolve()),
                "size_mb": round(stat.st_size / (1024 * 1024), 2),
                "created_at": datetime.fromtimestamp(stat.st_mtime).isoformat(),
                "preview_url": f"/media/videos/{f.name}",
                "thumbnail_url": thumb_url
            })

    # 2. Inspect generated Spotify Carousels
    if CAROUSELS_OUTPUT_DIR.exists():
        for folder in CAROUSELS_OUTPUT_DIR.iterdir():
            if folder.is_dir():
                slides = sorted([str(s.resolve()) for s in folder.glob("slide_*.png")])
                if slides:
                    stat = folder.stat()
                    carousels.append({
                        "folder_name": folder.name,
                        "slide_count": len(slides),
                        "slides": slides,
                        "preview_url": f"/media/carousels/{folder.name}/{Path(slides[0]).name}",
                        "created_at": datetime.fromtimestamp(stat.st_mtime).isoformat()
                    })

    # Sort newest first
    videos.sort(key=lambda x: x["created_at"], reverse=True)
    carousels.sort(key=lambda x: x["created_at"], reverse=True)

    return {
        "videos": videos,
        "carousels": carousels
    }
